services:
  onlinechat.redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: mysql_chat
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 2022
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: